### ISSUE TITLE
Support template filter safe

### ISSUE THREAD

**Issue by mkoertgen** [awesome-inc/neo4j-decorator#12]
We ran across an issue where we needed to html-escape a document value to be interpolated.

Should switch to a grown templating engine instead of the home-grown interpolation, e.g. [nunjucks](https://mozilla.github.io/nunjucks/)

We would love to use

```yml
...
body:
  query: ".... {{ doc.data.name | urlencode }}"
```

See [urlencode filter](https://mozilla.github.io/nunjucks/templating.html#urlencode) in nunjucks
